DTA.Web/Controllers/AdminDashboardController.cs
using DTA.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTA.Entities;
using System.Data.Entity;
using DTA.Services;

namespace DTA.Web.Controllers
{
    public class AdminDashboardController : Controller
    {
        private GenericRepository<OrderItem> db = new GenericRepository<OrderItem>();
        private GenericRepository<Category> cat = new GenericRepository<Category>();
        // GET: AdminDashboard
        public ActionResult Index()
        {
            ViewBag.Message = "Admin Dashboard";
            var categories = cat.GetAll(c => c.Books).ToList();

            return View(categories);
        }

        public ActionResult Orders()
        {
            var orders = db.GetAll().ToList();
            return View(orders);
        }
    }
}

DTA.Web/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DTA.Database;
using DTA.Entities;
using DTA.Services;
using PagedList;

namespace DTA.Web.Controllers
{
    public class AuthorsController : Controller
    {
        private GenericRepository<Author> db = new GenericRepository<Author>();

        // GET: Authors        
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            var authors = from a in db.GetAll()
                          select a;

            ViewBag.CurrentSort = sortOrder;
            ViewBag.FirstNameSortParm = String.IsNullOrEmpty(sortOrder) ? "fname_desc" : "";
            ViewBag.LastNameSortParm = sortOrder == "lname_asc" ? "lname_desc" : "lname_asc";


            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                authors = authors.Where(a => a.FirstName.ToUpper().Contains(searchString.ToUpper())
                                       || a.LastName.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "fname_desc":
                    authors = authors.OrderByDescending(a => a.FirstName);
                    break;
                case "lname_desc":
                    authors = authors.OrderByDescending(a => a.LastName);
                    break;
                case "lname_asc":
                    authors = authors.OrderBy(a => a.LastName);
                    break;
                default:
                    authors = authors.OrderBy(a => a.FirstName);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(authors.ToPagedList(pageNumber, pageSize));          

        }

        // GET: Authors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.GetById(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // GET: Authors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AuthorId,FirstName,LastName")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Insert(author);
                db.Save();
                return RedirectToAction("Index");
            }

            return View(author);
        }

        // GET: Authors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.GetById(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AuthorId,FirstName,LastName")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Update(author);
                db.Save();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.GetById(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.Delete(id);
            db.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose(disposing);
            }
            base.Dispose(disposing);
        }
    }
}

DTA.Web/Controllers/BooksController.cs
using System;
using System.Data;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DTA.Entities;
using DTA.Services;
using DTA.Services.Repository;
using DTA.Web.Filters;
using DTA.Web.ViewModels;
using PagedList;

namespace DTA.Web.Controllers
{
    //[Authorize(Roles ="Admin")]
    public class BooksController : Controller
    {
        private GenericRepository<Book> db = new GenericRepository<Book>();

        // GET: Books
        [Log]
        public ActionResult Index(string sortingParameter = "Default Order", string groupingParameter = "All", int minPrice = 1, int maxPrice = 100, int? page = null, string searchString = "")
        {
            SortContextClass sortContext;
            BooksViewModel booksViewModel = new BooksViewModel();
            if (minPrice > maxPrice)
            {
                var temp = minPrice;
                minPrice = maxPrice;
                maxPrice = temp;
            }
            
            var books = db.GetAll(b => b.Author, b => b.Category).ToList();
            if (sortingParameter != "Default Order")
            {
                switch (sortingParameter)
                {
                    case "Price(ASC)":
                        sortContext = new SortContextClass(new SortByPriceAscending());
                        books = sortContext.SortTheBooks(books);
                        break;
                    case "Price(DESC)":
                        sortContext = new SortContextClass(new SortByPriceDescending());
                        books = sortContext.SortTheBooks(books);
                        break;
                    case "Title(A-Z)":
                        sortContext = new SortContextClass(new SortByTitleAscending());
                        books = sortContext.SortTheBooks(books);
                        break;
                    case "Title(Z-A)":
                        sortContext = new SortContextClass(new SortByTitleDescending());
                        books = sortContext.SortTheBooks(books);
                        break;
                }
            }
            Session["currentSearchString"] = searchString;
            Session["currentmaxPrice"] = maxPrice;
            Session["currentminPrice"] = minPrice;
            Session["currentSorting"] = sortingParameter;
            Session["currentGrouping"] = groupingParameter;
            if (Session["currentGrouping"] != null && Session["currentGrouping"].ToString() != "All")
            {
                books = books.Where(x => x.Category.Title == groupingParameter).ToList();
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                books = books.Where(b => b.Title.ToUpper().Contains(searchString.ToUpper())).ToList();

                //|| b.Author.FirstName.Contains(searchString)              
            }
            books = books.Where(x => x.Price >= minPrice && x.Price <= maxPrice).ToList();
            
            int pageSize = 9;
            int pageNumber = (page ?? 1);
            booksViewModel.Books = books.ToPagedList(pageNumber, pageSize);
            var categories = new GenericRepository<Category>().GetAll();
            foreach (var item in categories)
            {
                int count = books.Count(x => x.Category.Title == item.Title);
                booksViewModel.Categories.Add(item.Title, count);
            }
            return View(booksViewModel);
        }

        // GET: Books
        public ActionResult AdminIndex(string sortOrder, string searchString, string currentFilter, int? page)
        {
            var books = db.GetAll(b => b.Author, b => b.Category);

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                books = books.Where(b => b.Title.ToUpper().Contains(searchString.ToUpper())
                                       || b.Author.FirstName.ToUpper().Contains(searchString.ToUpper())
                                       || b.Author.LastName.ToUpper().Contains(searchString.ToUpper())
                                       || b.Category.Title.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    books = books.OrderByDescending(b => b.Title);
                    break;
                default:
                    books = books.OrderBy(b => b.Title);
                    break;
            }

            int pageSize = 12;
            int pageNumber = (page ?? 1);
            return View(books.ToPagedList(pageNumber, pageSize));

        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.GetById(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Books/AdminDetails/5
        public ActionResult AdminDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.GetById(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            populateAuthorsDrobDownList();
            populateCategoriesDrobDownList();
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookId,Cover,Title,Price,ISBN,YearPublished,Language,Description,AuthorId,CategoryId")] Book book, HttpPostedFileBase postedFile)
        {
            if (postedFile != null)
            {
                try
                {
                    var cover = postedFile;
                    cover.SaveAs(Server.MapPath("~/Covers/" + cover.FileName));
                    book.Cover = "~/Covers/" + cover.FileName;
                    if (ModelState.IsValid)
                    {
                        db.Insert(book);
                        db.Save();
                        return RedirectToAction("Index");
                    }
                }
                catch (RetryLimitExceededException)
                {
                    
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            else
            {
                book.Cover = "~/Covers/ComingSoon.png";
                if (ModelState.IsValid)
                {
                    db.Insert(book);
                    db.Save();
                    return RedirectToAction("AdminIndex");
                }
            }
            populateAuthorsDrobDownList(book.AuthorId);
            populateCategoriesDrobDownList(book.CategoryId);
            return View(book);
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.GetById(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            TempData["oldCoverDir"] = book.Cover;
            ViewBag.AuthorId = new SelectList(new GenericRepository<Author>().GetAll(), "AuthorId", "FirstName", book.AuthorId);
            ViewBag.CategoryId = new SelectList(new GenericRepository<Category>().GetAll(), "CategoryId", "Title", book.CategoryId);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookId,Cover,Title,Price,ISBN,YearPublished,Language,Description,AuthorId,CategoryId")] Book book, HttpPostedFileBase postedFile)
        {
            if (postedFile != null)
            {
                var cover = postedFile;
                cover.SaveAs(Server.MapPath("~/Covers/" + cover.FileName));
                book.Cover = "~/Covers/" + cover.FileName;
            }
            else
            {
                book.Cover = TempData["oldCoverDir"].ToString();
            }
            if (ModelState.IsValid)
            {
                db.Update(book);
                db.Save();
                return RedirectToAction("AdminIndex");
            }
            ViewBag.AuthorId = new SelectList(new GenericRepository<Author>().GetAll(), "AuthorId", "FirstName", book.AuthorId);
            ViewBag.CategoryId = new SelectList(new GenericRepository<Category>().GetAll(), "CategoryId", "Title", book.CategoryId);
            return View(book);
        }

        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.GetById(id);

DTA.Web/Controllers/SalesController.cs
using System.Web.Mvc;
using PayPal.Api;

namespace BeerPal.Controllers
{
    public class SalesController : Controller
    {
        public ActionResult Index()
        {
            var apiContext = GetApiContext();

            var sales = Payment.List(apiContext);

            return View(sales);
        }

        public ActionResult Refund(string saleId)
        {
            var apiContext = GetApiContext();

            var sale = new Sale()
            {
                id = saleId
            };

            // A refund with no details refunds the entire amount.
            var refund = sale.Refund(apiContext, new Refund());

            return RedirectToAction("Index");
        }

        private APIContext GetApiContext()
        {
            // Authenticate with PayPal
            var config = ConfigManager.Instance.GetProperties();
            var accessToken = new OAuthTokenCredential(config).GetAccessToken();
            var apiContext = new APIContext(accessToken);
            return apiContext;
        }
    }
}

DTA.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link href="~/Content/all.css" rel="stylesheet" />
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Favicon -->
    <link rel="shortcut icon" href="~/images/favicon.ico">
    <!-- overlayScrollbars -->
    <link href="~/css/plugins/OverlayScrollbars.css" rel="stylesheet" />
    <!-- Theme style -->
    <link href="~/css/adminIte.css" rel="stylesheet" />
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item d-none d-sm-inline-block">
                    @Html.ActionLink("Back to store", "Index", "Home", new object { }, new { @class = "nav-link" })
                </li>
            </ul>

        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="@Url.Action("Index", "Home")" class="brand-link">
                <img src="~/images/logo/logo.png"
                     alt="Bookstor Logo"
                     class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">BOOKSTOR</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="info">
                        @using Microsoft.AspNet.Identity                        
                        <a href="#" class="d-block">@Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item">
                            @Html.ActionLink("    Home", "Index", "AdminDashboard", new object { }, new { @class = "nav-link fa fa-bars" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink(" Orders", "Orders", "AdminDashboard", new object { }, new { @class = "nav-link fa fa-arrow-right" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink(" Payments and Refunds", "Index", "Sales", new object { }, new { @class = "nav-link fa fa-arrow-right" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink(" Edit Books", "AdminIndex", "Books", new object { }, new { @class = "nav-link fa fa-arrow-right" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink(" Edit Authors", "Index", "Authors", new object { }, new { @class = "nav-link fa fa-arrow-right" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink(" Edit Categories", "Index", "Categories", new object { }, new { @class = "nav-link fa fa-arrow-right" })
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
           
            <br />

            @RenderBody()

        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <strong>Copyright &copy; @DateTime.Now.Year - BookstoreAfdEmp.</strong> All rights reserved.
        </footer>

    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/js/vendor/jquery-3.2.1.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/js/jquery.overlayScrollbars.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/js/demo.js"></script>
</body>
</html>

DTA.Web/Views/Shared/_Footer.cshtml
<footer id="wn__footer" class="footer__area bg__cat--8 brown--color">
    <div class="footer-static-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer__widget footer__menu">
                        <div class="ft__logo">
                            <a href="@Url.Action("Index", "Home")">
                                <img src="~/images/logo/3.png" alt="logo">
                            </a>
                        </div>
                        <div class="footer__content">
                            <ul class="social__net social__net--2 d-flex justify-content-center">
                                <li><a href="https://www.facebook.com/afdemp/"><i class="bi bi-facebook"></i></a></li>
                                <li><a href="https://www.google.com"><i class="bi bi-google"></i></a></li>
                                <li><a href="https://twitter.com/AFDEmpNews"><i class="bi bi-twitter"></i></a></li>
                                <li><a href="https://www.linkedin.com/company/alliance-for-digital-employability/"><i class="bi bi-linkedin"></i></a></li>
                                <li><a href="https://www.youtube.com/channel/UC-BwnjnumUpmfI7nrPMSx3Q"><i class="bi bi-youtube"></i></a></li>
                            </ul>
                            <ul class="mainmenu d-flex justify-content-center">
                                <li>@Html.ActionLink("All Products", "Index", "Books")</li>
                                <li>@Html.ActionLink("My Account", "Index", "Manage")</li>
                                <li>@Html.ActionLink("LiveChat", "Chat", "Home")</li>                                
                                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                <li>@Html.ActionLink("For Developers", "GetApi", "Home")</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright__wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <div class="copyright">
                        <div class="copy__right__inner text-left">
                            <p>Copyright &copy; @DateTime.Now.Year - BookstoreAfdEmp. All Rights Reserved</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <div class="payment text-right">
                        <img src="~/images/icons/payment.png" alt="" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

DTA.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - BOOKSTOR</title>
    @Scripts.Render("~/bundles/modernizr")

    <!-- Favicons -->
    <link rel="shortcut icon" href="~/images/favicon.ico">
    <link rel="apple-touch-icon" href="~/images/icon.png">

    <!-- Google font (font-family: 'Roboto', sans-serif; Poppins ; Satisfy) -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,500,600,600i,700,700i,800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">

    <!-- Stylesheets -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/plugins.css">
    <link rel="stylesheet" href="~/css/style.css">

    <!-- Custom css -->
    @*<link rel="stylesheet" href="css/custom.css">*@

    <!-- Modernizer js -->
    <script src="~/js/vendor/modernizr-3.5.0.min.js"></script>

</head>
<body>
    <div class="wrapper" id="wrapper">
        
        @Html.Partial("_Header")

        <section>

            @RenderBody()

            <hr />

            @Html.Partial("_Footer")   
            
        </section>


    </div>
    <script>
       var xElement = document.getElementById("CartIcon");
        xElement.innerHTML = sessionStorage.clickcount || 0;

        

        function increaseCartIcon() {
            if (document.getElementById("qty") !== null) {
                var quantityValue = document.getElementById("qty").value || 1;
            } else {
                var quantityValue =1;
            }
            if (typeof (Storage) !== "undefined") {
                if (sessionStorage.clickcount) {
                    sessionStorage.clickcount = Number(sessionStorage.clickcount) + Number(quantityValue);
                } else {
                    sessionStorage.clickcount = 1;
                }
                document.getElementById("CartIcon").innerHTML = sessionStorage.clickcount;
            } else {
                document.getElementById("CartIcon").innerHTML = "Sorry, your browser does not support web storage...";
            }
        }
        
        
        //function updateCartIcon(bookId) {
        //     var x = document.getElementById(bookId);
        //     if (Number(sessionStorage.clickcount) > 0) {
        //         sessionStorage.clickcount = (sessionStorage.clickcount) - x.value;
        //     }
        //     document.getElementById("CartIcon").innerHTML = sessionStorage.clickcount;
        //     alert("hello");
        //};
    </script>

    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/plugins.js"></script>
    <script src="~/js/Active.js"></script>
    
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>